
model:
  checkpoint: ./pretrained_models/pretrained_diffusion.pt
  model_mean_type: C0  # ['noise', 'C0']
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  v_beta_schedule: cosine
  v_beta_s: 0.01
  num_diffusion_timesteps: 1000
  loss_v_weight: 100.
  sample_time_method: symmetric  # ['importance', 'symmetric']

  time_emb_dim: 0
  time_emb_mode: simple
  center_pos_mode: protein

  node_indicator: True
  model_type: egnn # [uni_o2, egnn]
  num_layers: 2
  hidden_dim: 128
  edge_feat_dim: 4  # edge type feat
  num_r_gaussian: 20
  knn: 32 # was 32
  pool: add # [mean, max, add]
  cutoff_mode: knn  # [radius, none]

  ignore_pos: True
  num_encoder: 1
  num_heads: 8
  num_ffn: 128
  act_fn_ecd: ReLU
  dropout_r: 0.1
  num_ffn_head: 256


sample:
  classifier_type: c
  ckpt: /home/yuejian/project/targetaware/load_ckpt/escher
  seed: 2021
  num_samples: 100
  num_steps: 1000 # was 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior
  s: 30. # [0., 1., 5., 10.]
  s_v: 0. # [1., 5., 10.]
  context: -20. # [-7., -13.] mean at -10.5 for example pocket
  norm_type: l1
  clip: 1e10
  condition: -10.
  w: 0.

train:
  ckpt_dir: ./load_ckpt
  seed: 2021
  batch_size: 16 # was 4
  num_workers: 4
  n_acc_batch: 1
  max_iters: 20 # 10000000
  val_freq: 1
  ckpt_freq: 5
  pos_noise_std: 0.1
  max_grad_norm: 8.0
  bond_loss_weight: 1.0
  Lcutoff: -100000. # [-10.,-1000000.]
  Rcutoff: 0.
  loss_weight: 0.5
  optimizer:
    type: adam
    lr: 5.e-4
    weight_decay: 0
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.5
    patience: 2
    min_lr: 1.e-6
  loss:
    type: MSE # [MAE, MSE]
