# ckpt_dir_single: load_ckpt/t_condition_classifier/uniform_simple
model:
  checkpoint: ./pretrained_models/train_without_timeembed/dropp_2e-1/109200.pt
  model_mean_type: C0  # ['noise', 'C0']
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  v_beta_schedule: cosine
  v_beta_s: 0.01
  num_diffusion_timesteps: 1000
  loss_v_weight: 100.
  sample_time_method: symmetric  # ['importance', 'symmetric']

  time_emb_dim: 0
  time_emb_mode: simple
  center_pos_mode: protein

  node_indicator: True
  model_type: uni_o2 # [uni_o2, egnn]
  # num_blocks: 1
  num_layers: 2
  hidden_dim: 128
  # n_heads: 16
  edge_feat_dim: 4  # edge type feat
  num_r_gaussian: 20
  knn: 32 # was 32
  pool: add # [mean, max, add]
  # num_node_types: 8
  # act_fn: relu
  # norm: True
  cutoff_mode: knn  # [radius, none]
  # ew_net_type: global  # [r, m, none]
  # num_x2h: 1
  # num_h2x: 1
  # r_max: 10.
  # x2h_out_fc: False
  # sync_twoup: False

  # Added by Curtis
  ignore_pos: True
  num_encoder: 1
  num_heads: 8
  num_ffn: 128
  act_fn_ecd: ReLU
  dropout_r: 0.1
  num_ffn_head: 256

sample:
  classifier_type: c
  ckpt: ./load_ckpt/t_condition_classifier/uniform_sin
  seed: 2021
  num_samples: 100
  num_steps: 1000 # was 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior
  s: 0. # [0., 1., 5., 10.]
  s_v: 0. # [1., 5., 10.]
  context: -15. # [-7., -13.] mean at -10.5 for example pocket
  clip: 1e10
  condition: -15.
  w: 15. # -1, uncond; 0, cond
  norm_type: l2

train:
  ckpt_dir: ./load_ckpt
  seed: 2021
  batch_size: 16 # was 4
  num_workers: 4
  n_acc_batch: 1
  max_iters: 20 # 10000000
  val_freq: 1
  ckpt_freq: 5
  pos_noise_std: 0.1
  max_grad_norm: 8.0
  bond_loss_weight: 1.0
  Lcutoff: -100000. # [-10.,-1000000.]
  Rcutoff: 0.
  loss_weight: 0.5
  null_indicator: -20. # useless, disable
  optimizer:
    type: adam
    lr: 5.e-4
    weight_decay: 0
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.5
    patience: 2
    min_lr: 1.e-6
  loss:
    type: MSE # [MAE, MSE]
