data:
  name: pl
  path: ./data/crossdocked_v1.1_rmsd1.0_pocket10
  split: ./data/crossdocked_pocket10_pose_split_comb.pt
  transform:
    ligand_atom_mode: add_aromatic
    random_rot: False

model:
  checkpoint: ./pretrained_models/pretrained_diffusion.pt
  model_mean_type: C0  # ['noise', 'C0']
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  v_beta_schedule: cosine
  v_beta_s: 0.01
  num_diffusion_timesteps: 1000
  loss_v_weight: 100.
  sample_time_method: symmetric  # ['importance', 'symmetric']

  time_emb_dim: 0
  time_emb_mode: simple
  center_pos_mode: protein

  node_indicator: True
  model_type: egnn # [uni_o2, egnn]
  num_layers: 2
  hidden_dim: 128
  edge_feat_dim: 4  # edge type feat
  num_r_gaussian: 20
  knn: 32 # was 32
  pool: add # [mean, max, add]
  cutoff_mode: knn  # [radius, none]

  ignore_pos: True
  num_encoder: 1
  num_heads: 8
  num_ffn: 128
  act_fn_ecd: ReLU
  dropout_r: 0.1
  num_ffn_head: 256

train:
  ckpt_dir: ./load_ckpt
  seed: 2021
  batch_size: 32 # was 4
  num_workers: 1
  n_acc_batch: 1
  max_iters: 60 # 10000000
  val_freq: 1
  ckpt_freq: 5
  pos_noise_std: 0.1
  max_grad_norm: 8.0
  bond_loss_weight: 1.0
  Lcutoff: -100000. # [-10.,-1000000.]
  Rcutoff: 0.
  loss_weight: 0.5
  optimizer:
    type: adam
    lr: 2.5e-4
    weight_decay: 0
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: warmup_plateau
    factor: 0.6
    patience: 2
    min_lr: 1.e-6
    multiplier: 1
    total_epoch: 5 # change this manuallyscheduler:
    threshold: 0.1
  loss:
    type: MSE # [MAE, MSE]
